name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - run: sudo apt-get update && sudo apt-get install -y graphviz
      - run: sbt test
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - run: sbt publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
